name: Build LKM
on:
  workflow_dispatch:

jobs:
  build-lkm:
    uses: ./.github/workflows/gki-kernel.yml
    with:
      version: android13-5.10
      version_name: android13-5.10.189
      tag: android13-5.10-2023-11
      os_patch_level: 2023-11
      module_dir: pvm
      module_name: pvm
      module_config: PVM_MOD
      build_lkm: true
